apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.back.entryPoints: web
    traefik.http.routers.back.rule: Host(`api.officesg.forsg.io`)
    traefik.http.services.back.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.back.entryPoints: web
        traefik.http.routers.back.rule: Host(`api.officesg.forsg.io`)
        traefik.http.services.back.loadbalancer.server.port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          env:
            - name: ADMIN_API_TOKEN
            - name: ALLOW_ARTILLERY
              value: "true"
            - name: BBB_SECRET
            - name: BBB_URL
            - name: DEBUG
              value: '*'
            - name: EJABBERD_API_URI
              value: http://ejabberd:5443/api/
            - name: EJABBERD_DOMAIN
            - name: EJABBERD_PASSWORD
            - name: EJABBERD_USER
            - name: ENABLE_CHAT
            - name: ENABLE_CHAT_UPLOAD
            - name: ENABLE_FEATURE_MAP_EDITOR
            - name: JITSI_ISS
            - name: JITSI_URL
            - name: MAP_STORAGE_URL
              value: map-storage:50053
            - name: MAX_PER_GROUP
              value: MAX_PER_GROUP
            - name: NODE_ENV
              value: development
            - name: PLAYER_VARIABLES_MAX_TTL
            - name: PROMETHEUS_AUTHORIZATION_TOKEN
            - name: PUBLIC_MAP_STORAGE_URL
              value: http://map-storage.officesg.forsg.io
            - name: REDIS_HOST
              value: back-redis.default.svc.cluster.local
            - name: SECRET_JITSI_KEY
            - name: SECRET_KEY
              value: yourSecretKey
            - name: STARTUP_COMMAND_0
              value: touch /usr/src/app/back/src/Messages/generate_request/need_regenerate
            - name: STARTUP_COMMAND_1
              value: ../npm-install.sh
            - name: STARTUP_COMMAND_2
              value: while [ -f /usr/src/app/back/src/Messages/generate_request/need_regenerate ]; do sleep 1; done
            - name: STORE_VARIABLES_FOR_LOCAL_MAPS
              value: "true"
            - name: TURN_STATIC_AUTH_SECRET
              value: SomeStaticAuthSecret
          image: thecodingmachine/nodejs:v2-18-bullseye
          name: back
          ports:
            - containerPort: 9229
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: back-claim0
          workingDir: /usr/src/app/back
      restartPolicy: Always
      volumes:
        - name: back-claim0
          persistentVolumeClaim:
            claimName: back-claim0
status: {}
