apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.front.rule: Host(`front.officesg.forsg.io`)
    traefik.http.routers.front.service: front
    traefik.http.routers.play.priority: "1"
    traefik.http.routers.play.rule: HostRegexp(`{domain:.*}`)
    traefik.http.routers.play.service: play
    traefik.http.services.front.loadbalancer.server.port: "8080"
    traefik.http.services.play.loadbalancer.server.port: "3000"
  creationTimestamp: null
  labels:
    io.kompose.service: play
  name: play
spec:
  ports:
    - name: "9231"
      port: 9231
      targetPort: 9229
  selector:
    io.kompose.service: play
status:
  loadBalancer: {}
