apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.redisinsight.entryPoints: web
    traefik.http.routers.redisinsight.rule: Host(`redis.officesg.forsg.io`)
    traefik.http.services.redisinsight.loadbalancer.server.port: "8001"
  creationTimestamp: null
  labels:
    io.kompose.service: redisinsight
  name: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisinsight
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.redisinsight.entryPoints: web
        traefik.http.routers.redisinsight.rule: Host(`redis.officesg.forsg.io`)
        traefik.http.services.redisinsight.loadbalancer.server.port: "8001"
      creationTimestamp: null
      labels:
        io.kompose.service: redisinsight
    spec:
      containers:
        - image: redislabs/redisinsight:latest
          name: redisinsight
          resources: {}
      restartPolicy: Always
status: {}
