# Source: workadventure-chart/templates/service-back.yaml
apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    helm.sh/chart: workadventure-chart-0.1.17
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.2.7"
    app.kubernetes.io/managed-by: Helm
  annotations:
    external-dns.alpha.kubernetes.io/hostname: back.officesg.forsg.io
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 50051
      targetPort: direct
      protocol: TCP
      name: direct
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/type: "back"
---
# Source: workadventure-chart/templates/deployment-back.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    helm.sh/chart: workadventure-chart-0.1.17
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.2.7"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: workadventure-chart
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/type: "back"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workadventure-chart
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/type: "back"
    spec:
      serviceAccountName: release-name-workadventure-chart
      securityContext:
        {}
      containers:
        - name: back
          securityContext:
            {}
          image: {{CONTAINER_REGISTRY}}/officesg:back-{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: direct
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {}
          env:
            - name: 'DEBUG'
              value: "*"
            - name: 'SECRET_KEY'
              value: "tempSecretKeyNeedsToChange"
            - name: 'ADMIN_API_TOKEN'
              value: "123"
            - name: 'JITSI_ISS'
              value: ""
            - name: 'JITSI_URL'
              value: "meet.jit.si"
            - name: 'SECRET_JITSI_KEY'
              value: ""
              #TODO : ADMIN_API_URL

            - name: KEY
              value: value
---
# Source: workadventure-chart/templates/hpa-back.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: back
  labels:
    helm.sh/chart: workadventure-chart-0.1.17
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.2.7"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80