apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: messages
  name: messages
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messages
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: messages
    spec:
      containers:
        - env:
            - name: STARTUP_COMMAND_1
              value: npm install
            - name: STARTUP_COMMAND_2
              value: npm run proto:watch
          image: thecodingmachine/workadventure-back-base:v1-18
          name: messages
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: messages-claim0
            - mountPath: /usr/src/back
              name: messages-claim1
            - mountPath: /usr/src/play
              name: messages-claim2
            - mountPath: /usr/src/chat
              name: messages-claim3
            - mountPath: /usr/src/map-storage
              name: messages-claim4
            - mountPath: /usr/src/libs
              name: messages-claim5
      restartPolicy: Always
      volumes:
        - name: messages-claim0
          persistentVolumeClaim:
            claimName: messages-claim0
        - name: messages-claim1
          persistentVolumeClaim:
            claimName: messages-claim1
        - name: messages-claim2
          persistentVolumeClaim:
            claimName: messages-claim2
        - name: messages-claim3
          persistentVolumeClaim:
            claimName: messages-claim3
        - name: messages-claim4
          persistentVolumeClaim:
            claimName: messages-claim4
        - name: messages-claim5
          persistentVolumeClaim:
            claimName: messages-claim5
status: {}
