apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.front.rule: Host(`front.{{SERVICE_DOMAIN}}`)
    traefik.http.routers.front.service: front
    traefik.http.routers.play.priority: "1"
    traefik.http.routers.play.rule: HostRegexp(`{domain:.*}`)
    traefik.http.routers.play.service: play
    traefik.http.services.front.loadbalancer.server.port: "8080"
    traefik.http.services.play.loadbalancer.server.port: "3000"
  creationTimestamp: null
  labels:
    io.kompose.service: play
  name: play
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: play
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.front.rule: Host(`front.{{SERVICE_DOMAIN}}`)
        traefik.http.routers.front.service: front
        traefik.http.routers.play.priority: "1"
        traefik.http.routers.play.rule: HostRegexp(`{domain:.*}`)
        traefik.http.routers.play.service: play
        traefik.http.services.front.loadbalancer.server.port: "8080"
        traefik.http.services.play.loadbalancer.server.port: "3000"
      creationTimestamp: null
      labels:
        io.kompose.service: play
    spec:
      containers:
#        - args:
#            - npm
#            - run
#            - start #change from dev to start
        - env:
            - name: ADMIN_API_TOKEN
            - name: ALLOWED_CORS_ORIGIN
#              value: http://play.{{SERVICE_DOMAIN}}
              value: "*"
            - name: API_URL
#              value: back:50051
              value: api.{{SERVICE_DOMAIN}}:50051
            - name: CHAT_URL
              value: https://chat.{{SERVICE_DOMAIN}}
            - name: DEBUG
              value: socket:*
            - name: DEBUG_ERROR_MESSAGES
              value: "true"
            - name: DEBUG_MODE
            - name: DISABLE_ANONYMOUS
            - name: DISABLE_NOTIFICATIONS
            - name: EJABBERD_DOMAIN
              value: "ejabberd"
            - name: EJABBERD_JWT_SECRET
              value: {{EJABBERD_JWT_SECRET}}
            - name: ENABLE_CHAT
              value: "true"
            - name: ENABLE_CHAT_DISCONNECTED_LIST
              value: "true"
            - name: ENABLE_CHAT_ONLINE_LIST
              value: "true"
            - name: ENABLE_CHAT_UPLOAD
            - name: ENABLE_FEATURE_MAP_EDITOR
            - name: ENABLE_OPENAPI_ENDPOINT
              value: "true"
            - name: HOST
              value: 0.0.0.0
            - name: ICON_URL
              value: https://icon.{{SERVICE_DOMAIN}}
            - name: JITSI_PRIVATE_MODE
            - name: JITSI_URL
              value: "meet.jit.si"
            - name: MAX_PER_GROUP
            - name: MAX_USERNAME_LENGTH
            - name: NODE_ENV
              value: production
            - name: OPID_CLIENT_ID
            - name: OPID_CLIENT_ISSUER
            - name: OPID_CLIENT_SECRET
            - name: OPID_LOCALE_CLAIM
            - name: OPID_LOGOUT_REDIRECT_URL
            - name: OPID_PROFILE_SCREEN_PROVIDER
            - name: OPID_PROMPT
            - name: OPID_SCOPE
            - name: OPID_USERNAME_CLAIM
            - name: PLAY_URL
              value: https://play.{{SERVICE_DOMAIN}}
            - name: PUBLIC_MAP_STORAGE_URL
              value: https://map-storage.{{SERVICE_DOMAIN}}
            - name: SECRET_KEY
              value: yourSecretKey
            - name: SERVER_ICON
            - name: SERVER_MOTD
            - name: SERVER_NAME
            - name: SKIP_RENDER_OPTIMIZATIONS
#            - name: STARTUP_COMMAND_0
#              value: touch /usr/src/app/play/src/messages/generate_request/need_regenerate
#            - name: STARTUP_COMMAND_1
#              value: ../npm-install.sh
#            - name: STARTUP_COMMAND_2
#              value: npm run typesafe-i18n
#            - name: STARTUP_COMMAND_5
#              value: while [ -f /usr/src/app/play/src/messages/generate_request/need_regenerate ]; do sleep 1; done
            - name: START_ROOM_URL
            - name: STUN_SERVER
              value: stun:stun.l.google.com:19302
            - name: TURN_PASSWORD
#              value: "WorkAdventure123"
              value: "openrelayproject"
            - name: TURN_SERVER
#              value: turn:coturn.{{SERVICE_DOMAIN}}:3478,turns:coturn.{{SERVICE_DOMAIN}}:5349
#              value: turn:coturn.workadventu.re:443,turns:coturn.workadventu.re:443
              value: turn:openrelay.metered.ca:80
            - name: TURN_USER
#              value: "workadventure"
              value: "openrelayproject"
            - name: UPLOADER_URL
              value: https://uploader.{{SERVICE_DOMAIN}}
            - name: VITE_URL
              value: https://front.{{SERVICE_DOMAIN}}
          #          image: thecodingmachine/nodejs:v2-18-bullseye
          image: {{CONTAINER_REGISTRY}}/officesg:play-{{VERSION}}
          name: play
          ports:
#            - containerPort: 9229
            - name: http
              containerPort: 3000
#              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 2000m
              memory: 10000Mi
          #          volumeMounts:
          #            - mountPath: /usr/src/app
          #              name: play-claim0
#          workingDir: /usr/src/app/play
      restartPolicy: Always
#      volumes:
#        - name: play-claim0
#          persistentVolumeClaim:
#            claimName: play-claim0
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.front.rule: Host(`front.{{SERVICE_DOMAIN}}`)
    traefik.http.routers.front.service: front
    traefik.http.routers.play.priority: "1"
    traefik.http.routers.play.rule: HostRegexp(`{domain:.*}`)
    traefik.http.routers.play.service: play
    traefik.http.services.front.loadbalancer.server.port: "8080"
    traefik.http.services.play.loadbalancer.server.port: "3000"
  creationTimestamp: null
  labels:
    io.kompose.service: play
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
  name: play
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    io.kompose.service: play
status:
  loadBalancer: {}
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: http
#      protocol: TCP
#      name: http
#    - port: 443
#      targetPort: http
#      protocol: TCP
#      name: https
#  selector:
#    app.kubernetes.io/name: workadventure-chart
#    app.kubernetes.io/instance: release-name
#    app.kubernetes.io/type: "play"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: play
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: play
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: play
  labels:
    app.kubernetes.io/name: workadventure-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.2.7"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - play.{{SERVICE_DOMAIN}}
      secretName: front-tls
  rules:
    - host: play.{{SERVICE_DOMAIN}}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: play
                port:
                  number: 80
