#
# GitHub Actions workflow.
#
# Deploys the back-redis database.
#

name: Deploy back-redis demo

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
          aws-region: ap-southeast-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0'
        id: install

      - name: Update kube config
        run: aws eks update-kubeconfig --name my-demo-cluster-officesg --region ap-southeast-1
      - name: Print kubectl logs for debugging
        run: |
          kubectl get pods

      #
      # Deploys the gopro Postgres database to Kubernetes.
      #
      - name: Deploy
        run: kubectl apply -f ./scripts/kubernetes/back-redis.yaml
